sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
#  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl1.2-dev
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - wget http://accellera.org/images/downloads/standards/systemc/systemc-2.3.1.tgz
  - tar -zxvf systemc-2.3.1.tgz
  - SYSTEMC_INSTALL=${MY_LOCATION}/systemc_install
  - export SYSTEMC_INSTALL
  - mkdir $SYSTEMC_INSTALL
  - cd systemc-2.3.1
  - mkdir objdir
  - cd objdir/
  - ../configure --prefix=$SYSTEMC_INSTALL
  - make -j
  - make install
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - git clone https://github.com/quicky2000/EXT_systemc
  - git clone https://github.com/quicky2000/quicky_exception
  - git clone https://github.com/quicky2000/simple_gui
  - git clone https://github.com/quicky2000/synoptic
  - cd quicky_tools/setup
  - . setup.sh
  - LD_LIBRARY_PATH=${SYSTEMC_INSTALL}/lib-linux64:${LD_LIBRARY_PATH}
  - export LD_LIBRARY_PATH
  - cd $MY_LOCATION\
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - generate_makefile sudoku_systemc
  - make
  - ./bin/sudoku_systemc.exe 10 > run.log
  - tail -30 run.log
  - echo "SUCCES"
#EOF
